### PR TITLE
[Stack Monitoring] Implementing diff in parity tests using dictdiffer

### LINKED ISSUE #315: [Stack Monitoring] Revisit diff algorithm in parity tests
Thanks to a change that @cachedout made in https://github.com/elastic/elastic-stack-testing/pull/313, we [found](https://github.com/elastic/elastic-stack-testing/pull/313#discussion_r321544127) some "interesting" properties of the diff'ing utility  we're using in our parity tests. For details, see this thread: https://github.com/elastic/elastic-stack-testing/pull/313#discussion_r321544127.

This issue is to track whether we're doing enough with the current diff algorithm and make any changes, if necessary.

### PR DESCRIPTION
**Pull request by ycombinator**
Resolves #315.

This PR makes the following key changes to the various `docs_compare.py` parity testing scripts for each product (Elasticsearch, Kibana, etc.):

1. It re-implements the diff'ing algorithm used by the parity testing scripts. The scripts now use a utility named [dictdiffer](https://pypi.org/project/dictdiffer/), which reports additions and removals in a fashion more useful for parity tests.

   For instance, consider the following difference:

   ```
   a = {'a': {'z': 'c'}}
   b = {'a': {'b': 'd'}}
   ```

   The previous implementation, which used [jsondiff](https://pypi.org/project/jsondiff/), would report the difference as follows:

   ```
   >>> diff(a,b, syntax='explicit', marshal=True)
   {'$update': {'a': {'b': 'd'}}}
   ```

   Whereas, the new implementation in this PR reports the same difference as follows:

   ```
   >>> list(diff(a,b))
   [('add', 'a', [('b', 'd')]), ('remove', 'a', [('z', 'c')])]
   ```
   (The `list` casting is necessary because `diff` returns a generator).

2. Given the new diffing utility's reporting, it reimplements the fix done in #313 (to be forward-ported to `master` in #316). The implementation in this PR tries to pull out the ILM policy introduced by Metricbeat based on certain properties of that policy, not based on the position of the policy in the list of policy stats, since there's no guarantee that the position may be the same every time.

3. It builds on the refactoring done in #347 by extracting even more common code used by all products' parity tests into the `docs_compare_util` module. Now each product's `docs_compare.py` script only contains code specific to that product.

### CODE REVIEW

**Comment by ycombinator** [comment]
@cachedout @liza-mae When I try to run parity tests with this PR locally like so:

```
AIT_STACK_PRODUCT=elasticsearch ./playbooks/monitoring/buildenv.sh
```

I get the following error on the last step:

```
Traceback (most recent call last):
  File "/Users/shaunak/development/github/elastic-stack-testing/playbooks/monitoring/elasticsearch/docs_compare.py", line 6, in <module>
    from docs_compare_util import check_parity
  File "/Users/shaunak/development/github/elastic-stack-testing/playbooks/monitoring/common/docs_compare_util.py", line 5, in <module>
    from dictdiffer import diff
ModuleNotFoundError: No module named 'dictdiffer'
```

AFAIK I have installed the `dictdiffer` package:

```
$ pip install dictdiffer
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Requirement already satisfied: dictdiffer in /usr/local/lib/python2.7/site-packages (0.8.0)
```

I suspect this has something to do with different Python versions but, first, I'd like to know if either of you are able to reproduce this error locally as well.

**Comment by liza-mae** [comment]
@ycombinator I have not seen this and we should be using python3.6, see [.python-version](https://github.com/elastic/elastic-stack-testing/blob/master/.python-version)

**Comment by liza-mae** [comment]
Please add dictdiffer in [requirements.txt](https://github.com/elastic/elastic-stack-testing/blob/master/requirements.txt) hopefully the package is compatible with python3 and try again.  buildenv.sh starts a virtual env.

**Comment by ycombinator** [comment]
Thanks @liza-mae, I forgot that buildenv.sh starts a virtualenv. Adding `dictdiffer` to `requirements.txt` did the trick. Appreciate your precise help, as always!

@cachedout This PR is ready for your review.

**Comment by ycombinator** [comment]
@cachedout With this PR merged into `master` now, I think we can close out #316. WDYT?

**Pull request merged**
