### PR TITLE
Ignoring unused index_stats.created field (for 7.x)

### PR DESCRIPTION
**Pull request by igoristic**
This was recently done for `7.13` https://github.com/elastic/elastic-stack-testing/pull/902, but forgot to account for `7.x`

Doesn't look like we are using `index_stats.created` anywhere in the SM kibana code.

Changes as a result of https://github.com/elastic/beats/pull/25113. The legacy collector (on the ES side) still creates the `index_stats.created` field thus breaking parity with the new modified metricbeat mapping.

Since, we do not use this field in our Kibana code base, we can remove it on the ES side https://github.com/elastic/elasticsearch/issues/73447

### CODE REVIEW

**Comment by jasonrhodes** [comment]
I didn't notice we were doing this on a 7.13 branch. Why didn't we do this against master and backport to 7.13 and 7.x?

**Comment by igoristic** [comment]
@jasonrhodes 
There's no concept of "backport" (what we have in kibana) in this repo, so we have to do it by hand.

Though we probably could've merged the same branch to the `7.13`, `7.x`, and `master`. Or, maybe there's a better way?

**Comment by jasonrhodes** [comment]
@igoristic yeah, the https://github.com/sqren/backport tool is a helper to do the `git cherry-pick` for you and create the PR, but it's possible to do without the tool. At any rate, we should probably make changes against `master` first, then figure out how to get those changes to the release branches -- I'm always happy to help. 

For now, let's close this, merge the `master` PR, and I can show you how to do the cherry pick.

**Comment by igoristic** [comment]
@jasonrhodes I would still need to create a new branch with

`git cherry-pick 958226a6b14fc868dc027c353c0a39e99fe0c3de`

958226a6b14fc868dc027c353c0a39e99fe0c3de

Not sure if that's what you meant, or if there's a difference from what I had before

**Comment by jasonrhodes** [comment]
`git cherry-pick` does not create a new branch.

**Comment by jasonrhodes** [comment]
@igoristic since you found that PR from Liza with a backport, can you reach out to her about how to best do that process in this repo? If she isn't available, ping me and I can help you with the cherry-pick from the commit that merged into master.

**Comment by igoristic** [comment]
@jasonrhodes Already did, and turns out we use the same https://github.com/sqren/backport tool. I'll have the backports up soon. Thanks!

**Comment by igoristic** [comment]
https://github.com/elastic/elastic-stack-testing/pull/922

**Pull request closed without merging**
