### PR TITLE
Avoid ignored failure on Include ait_action task files

### PR DESCRIPTION
**Pull request by matschaffer**
This also reuses the task_files lists so that we can avoid the duplication/sync.

The error that led me to this was

```
TASK [xpack_elasticsearch : Include ait_action task files] *********************
fatal: [aithost]: FAILED! => {}

MSG:

No file was found when using first_found. Use errors='ignore' to allow this task to be skipped if no files are found
...ignoring
```

When `ait_action` is unspecified. Seems like ansible resolves the `with_first_found` before the `when`.

The error doesn't seem to cause any harm, but added to my own confusion trying to work with ESTF. So I thought it might be good to try to fix it.

### CODE REVIEW

**Review by liza-mae — APPROVED** [review]
LGTM, thanks @matschaffer for cleaning up the ignore failure message

**Comment by matschaffer** [comment]
@liza-mae should I back port this to 8.0 or other branches? Or do we do that sort of ad-hoc/as-needed?

**Comment by liza-mae** [comment]
@matschaffer feel free to backport (the backport tool works in this repo) for active branches: 8.0 and 7.17

**Comment by matschaffer** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.0|[](https://github.com/elastic/elastic-stack-testing/pull/1108)|


### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Comment by matschaffer** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.0|[](https://github.com/elastic/elastic-stack-testing/pull/1108)|
|✅|7.17|[](https://github.com/elastic/elastic-stack-testing/pull/1109)|


### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Pull request merged**
