### PR TITLE
Replace references to "internal" with "legacy"

### PR DESCRIPTION
**Pull request by ycombinator**
In relatively recent times we've started referring to the method of each stack product collecting their own monitoring data and shipping it to the production Elasticsearch cluster as **legacy** collection/monitoring. Previously, we were referring to this method as **internal** collection/monitoring but now that term has taken on a different meaning.

This PR updates the parity tests — documentation, comments, and code — to reflect this change in terminology.

### CODE REVIEW

**Comment by chrisronline** [comment]
FWIW, this concept of "legacy" collection only exists for Beats. Our migration meta ticket does indicate that Logstash and Kibana will ship this concept of "internal" collection (in addition to still supporting "legacy" collection), but we have decided to not document this at this time, and will remove support for this in Logstash and Kibana in 7.8. 

Since it is looking like we're 100% bought into using Agent for monitoring (once it's GA), we do not want to introduce an additional form of monitoring collection that we will deprecate (when Agent is GA) and remove entirely in 8.0.

The meta ticket doesn't reflect this, as we are still in the decision phase but it's looking likely we will continue on the plan I described above.

As a result of this, I'm not sure how we should adapt the instructions here. We might need to change it so we don't generalize the concept but specify the correct terminology with each stack product. This might be more work than you wanted to chew off right now though.

WDYT?

**Comment by ycombinator** [comment]
I think we're on the same page. The plan is for products to support legacy collection (product => es prod => es mon) and `metricbeat` collection (product <= mb => es mon). Additionally, Beats also supports `internal` collection (product => es mon). My understanding is that when Agent comes around, it will either replace `metricbeat` collection or use `metricbeat` collection under the hood. 

If you agree with all of the above, then the changes in this PR are still applicable since it's inaccurate to say that the parity tests are using `internal` collection at any point - they setup products for `legacy` collection and `metricbeat `collection and then compare the results.

**Comment by ycombinator** [comment]
When we start supporting monitoring with Agent, we can revisit these tests. At that time we will probably want to change these tests to install+configure Agent instead of Metricbeat for monitoring. At that time we can decide whether we want to call this method of collection something new entirely, like `agent` collection or do something else.

Regardless, though, the _other_ collection method we'd always be comparing against is `legacy` collection, not `internal` collection. The latter is only supported in Beats. So I think we still need to go ahead with the changes in this PR to avoid confusion.

**Comment by chrisronline** [comment]
Yes true, but the term `legacy` collection will only appear in the Beats documentation, which might be confusing for new folks.

Perhaps at the top of the README, we can just clarify that the term `legacy` collection will be used throughout the documentation and that is consistent with the Beats documentation for monitoring, but inconsistent with Kibana/Logstash and to consider `legacy` and `internal` collection (for everything other than Beats) the same thing for the sake of the parity tests?

It's a mouth full though :(

**Comment by ycombinator** [comment]
> Yes true, but the term legacy collection will only appear in the Beats documentation, which might be confusing for new folks.

Right, and I think this is the source of the problem. Our product docs themselves are not aligned currently. We have the same exact method of collection (product => ES prod => ES mon) being described in three different ways:

1. Beats describes it as "legacy internal collection":
   Screen Shot 2020-04-28 at 7 37 00 AM

2. Logstash describes it as "internal collection":
   Screen Shot 2020-04-28 at 7 36 49 AM


3. ES and Kibana don't really use a specific term for it it at all 🙂 
   Screen Shot 2020-04-28 at 7 36 43 AM

   Screen Shot 2020-04-28 at 7 36 55 AM


I think we need to align the terminology in our product docs first, then use the same terminology in the parity tests (and other internal discussions/documentation).

WDYT?

**Comment by chrisronline** [comment]
@ycombinator Agreed, and sounds good. I can make issues for these, unless you want to ;)

**Comment by ycombinator** [comment]
@chrisronline go ahead, thanks 🙂. I'll pause on this PR until the product docs are all using the same terminology for the `product => ES prod => ES mon` collection method.

**Comment by chrisronline** [comment]
@ycombinator Do you think it's an issue that [the beats docs](https://www.elastic.co/guide/en/beats/filebeat/current/monitoring.html) use the phrase "Legacy internal collection"? Should we standardize on the phrase "Legacy collection" instead?

**Comment by ycombinator** [comment]
@chrisronline Yeah, we could change that to be just "legacy collection". I'd probably start a separate conversation with LizaC to hash out the preferred term and then, once you have a proposal, rope in tech writers for each of the products to get their thoughts.

**Comment by lcawl** [comment]
Had a quick chat with @dedemorton and @karenzone. Will circle back when there's agreement on a term we can use across the docs.

**Comment by ycombinator** [comment]
Hey @chrisronline Looking at the various docs PRs linking to this PR, it looks like we're lining up all our user-facing docs to use the term "legacy collection" for the `product => ES prod => ES mon` collection method.

Given that, I think this PR here is ready for review as-is.

**Pull request merged**
