### PR TITLE
Ignore some additional test artifacts

### PR DESCRIPTION
**Pull request by matschaffer**
During testing I noticed these came up as outstanding changes, so figured I should add them to gitignore.

### CODE REVIEW

**Comment by liza-mae** [comment]
Please see comment in referenced issue.

**Comment by jasonrhodes** [comment]
@liza-mae just checking, is there a downside to adding these to .gitignore? If we're responsible for helping to track down these test failures, I imagine we'll need the flexibility to do whatever we can to get them fixed, so I'd like to have the info Mat tracked down preserved until there is a better/official way to do these things.

**Comment by liza-mae** [comment]
@jasonrhodes it is not clear to me why the Cloud Kibana Flaky Test Runner in CI can't be used, the goal of providing that tool was to simplify the debugging process of failed tests.

**Review by liza-mae — APPROVED** [review]
LGTM

**Comment by matschaffer** [comment]
@jasonrhodes @liza-mae I've responded on https://github.com/elastic/observability-dev/pull/1992 since there's a bit more conversation there already.

**Pull request merged**
