### PR TITLE
Ignoring unused index_stats.created field

### PR DESCRIPTION
**Pull request by igoristic**
Doesn't look like we're using`index_stats.created` anywhere in the SM kibana code.

Changes as a result of https://github.com/elastic/beats/pull/25113. The legacy collector (on the ES side) still creates the `index_stats.created` field thus breaking parity with the new modified metricbeat mapping.

Since, we do not use this field in our Kibana code base, we can remove it on the ES side https://github.com/elastic/elasticsearch/issues/73447

### CODE REVIEW

**Comment by jasonrhodes** [comment]
@igoristic can you please update the description of this PR to explain what this .py script was doing, and what the "del" command was doing on the line that it was removed? Thanks!

I think this is probably related to this: https://github.com/elastic/beats/pull/25113#pullrequestreview-639053415

**Comment by igoristic** [comment]
@jasonrhodes I actually couldn't find the related PR (since I was looking in ES repo for recently added), so thank you for https://github.com/elastic/beats/pull/25113#pullrequestreview-639053415

The legacy collector (on the ES side) still creates the `index_stats.created` field thus breaking parity with the new modified metricbeat mapping.

Since, we do not use this field in our Kibana code base, we can also remove it on the ES side hence: https://github.com/elastic/elasticsearch/issues/73447

**Comment by jasonrhodes** [comment]
@igoristic thanks for filing the ES issue. Can you please update the description of this PR to explain what this .py script was doing, and what the "del" command was doing on the line that it was removed? It looks like it was already deleting the field, and we're now _not_ deleting it, but I don't know what that .py script does exactly so it's hard for me to say. Thanks!

**Comment by igoristic** [comment]
@jasonrhodes What do you mean by "removed"? 

This line: `del legacy_doc['index_stats']['created']` was **added** for reasons described in https://github.com/elastic/elastic-stack-testing/pull/902#issuecomment-849178901

**Comment by jasonrhodes** [comment]
Sorry, my fault for misreading. So do we not control the source of the legacy_doc? Would we remove this line once the ES change lands?

**Comment by igoristic** [comment]
@jasonrhodes No worries, I do it all the time 🙃 

> So do we not control the source of the legacy_doc? Would we remove this line once the ES change lands?

Indeed. Once ES removes those fields from SM template/mappings, we can remove/revert this code as well

**Review by jasonrhodes — APPROVED** [review]
Last question (I think): 

Are parity tests failing consistently this whole time while this PR is unmerged?

**Comment by igoristic** [comment]
> Are parity tests failing consistently this whole time while this PR is unmerged

Yep. Though, sometime they fail because vm box fails (or a caching issue)

**Comment by jasonrhodes** [comment]
Thanks! @igoristic can you link to a non-failing run of the parity tests here in the comments, when you have a chance, to prove this worked?

**Comment by igoristic** [comment]
Failing test before: https://internal-ci.elastic.co/job/elastic+estf-monitoring-snapshots+7.13+multijob-elasticsearch/68/consoleFull

Passing test after: https://internal-ci.elastic.co/job/elastic+estf-monitoring-snapshots+7.13+multijob-elasticsearch/69/consoleFull

**Pull request merged**
