### PR TITLE
[cherry-pick] Pull out the correct ILM entry

### PR DESCRIPTION
**Pull request by cachedout**
Forward merge of https://github.com/elastic/elastic-stack-testing/pull/313 to master branch

### CODE REVIEW

**Comment by ycombinator** [comment]
Forward port changes LGTM but, unfortunately, I have no way of actually testing them right now since we don't have a good `master` snapshot release. Once one of these is available, I'll test it with this PR.

**Comment by cachedout** [comment]
FWIW, I got a good snapshot this morning so this may be working now.

**Comment by ycombinator** [comment]
> FWIW, I got a good snapshot this morning so this may be working now.

Could you point me to the good snapshot's URL please? AFAICT we haven't had a good release snapshot from `master` for at least ~20 days or so.

Also, did you see my comment/question here: https://github.com/elastic/elastic-stack-testing/pull/353#issuecomment-532644536?

**Comment by cachedout** [comment]
> Could you point me to the good snapshot's URL please? AFAICT we haven't had a good release snapshot from master for at least ~20 days or so.

@ycombinator  I pulled snapshots from here this morning: https://artifacts-api.elastic.co/v1/branches/master

I missed the comment. Thanks for linking me to it. I have no objection to that and I'll close this.

**Pull request closed without merging**
